# Form implementation generated from reading ui file 'omengui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 722)
        MainWindow.setStyleSheet("Qwidget#QMainWindow{\n"
"title:\"Omen Sight\"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 911, 721))
        self.label.setMouseTracking(True)
        self.label.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 100, 901, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.URLinput = QtWidgets.QLineEdit(parent=self.frame)
        self.URLinput.setGeometry(QtCore.QRect(20, 70, 721, 31))
        self.URLinput.setMouseTracking(True)
        self.URLinput.setStyleSheet("QLineEdit{\n"
"border: 1px solid rgb(126, 126, 126);\n"
"color:rgb(231, 231, 231);\n"
"    font: 10pt \"Segoe UI\";\n"
"border-radius:5px;\n"
"}")
        self.URLinput.setFrame(False)
        self.URLinput.setObjectName("URLinput")
        self.ScanButton = QtWidgets.QPushButton(parent=self.frame)
        self.ScanButton.setGeometry(QtCore.QRect(750, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setItalic(False)
        self.ScanButton.setFont(font)
        self.ScanButton.setAutoFillBackground(False)
        self.ScanButton.setStyleSheet("color:rgb(25, 25, 25);\n"
"background-color: rgb(167, 167, 167);\n"
"font: 600 11pt \"Segoe UI\";")
        self.ScanButton.setDefault(False)
        self.ScanButton.setFlat(False)
        self.ScanButton.setObjectName("ScanButton")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 311, 16))
        self.label_2.setStyleSheet("color:rgb(189, 189, 189)")
        self.label_2.setObjectName("label_2")
        self.LiveButton = QtWidgets.QPushButton(parent=self.frame)
        self.LiveButton.setGeometry(QtCore.QRect(640, 105, 131, 30))
        self.LiveButton.setStyleSheet("color:rgb(25, 25, 25);\n"
"background-color: rgb(167, 167, 167);\n"
"font: 600 11pt \"Segoe UI\";")
        self.LiveButton.setObjectName("LiveButton")
        self.StopButton = QtWidgets.QPushButton(parent=self.frame)
        self.StopButton.setGeometry(QtCore.QRect(780, 105, 75, 30))
        self.StopButton.setStyleSheet("color:rgb(25, 25, 25);\n"
"background-color: rgb(167, 167, 167);\n"
"font: 600 11pt \"Segoe UI\";")
        self.StopButton.setObjectName("StopButton")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("static/policy_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.Heading = QtWidgets.QLabel(parent=self.centralwidget)
        self.Heading.setGeometry(QtCore.QRect(60, 10, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        font.setBold(True)
        self.Heading.setFont(font)
        self.Heading.setStyleSheet("Qwidget#Heading{\n"
"    font: 600 15pt \"Segoe UI\";\n"
"\n"
"}")
        self.Heading.setObjectName("Heading")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 250, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 600 10pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 270, 611, 391))
        self.textEdit.setMouseTracking(False)
        self.textEdit.setStyleSheet("border-color: rgb(134, 213, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"\n"
"font: 12pt \"Consolas\";")
        self.textEdit.setObjectName("textEdit")
        self.SQLcheck = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.SQLcheck.setGeometry(QtCore.QRect(630, 270, 121, 20))
        self.SQLcheck.setCheckable(True)
        self.SQLcheck.setChecked(True)
        self.SQLcheck.setTristate(False)
        self.SQLcheck.setObjectName("SQLcheck")
        self.XSScheck = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.XSScheck.setGeometry(QtCore.QRect(630, 300, 111, 20))
        self.XSScheck.setChecked(True)
        self.XSScheck.setObjectName("XSScheck")
        self.OpenRedirectcheck = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.OpenRedirectcheck.setEnabled(True)
        self.OpenRedirectcheck.setGeometry(QtCore.QRect(630, 330, 111, 20))
        self.OpenRedirectcheck.setChecked(True)
        self.OpenRedirectcheck.setObjectName("OpenRedirectcheck")
        self.SSLcheck = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.SSLcheck.setGeometry(QtCore.QRect(630, 360, 91, 20))
        self.SSLcheck.setChecked(True)
        self.SSLcheck.setObjectName("SSLcheck")
        self.SecurityHeadcheck = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.SecurityHeadcheck.setGeometry(QtCore.QRect(630, 390, 121, 20))
        self.SecurityHeadcheck.setChecked(True)
        self.SecurityHeadcheck.setObjectName("SecurityHeadcheck")
        self.label.raise_()
        self.frame.raise_()
        self.label_5.raise_()
        self.Heading.raise_()
        self.label_3.raise_()
        self.SQLcheck.raise_()
        self.XSScheck.raise_()
        self.OpenRedirectcheck.raise_()
        self.SSLcheck.raise_()
        self.SecurityHeadcheck.raise_()
        self.textEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(parent=MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ScanButton.setText(_translate("MainWindow", "Start Scan"))
        self.label_4.setText(_translate("MainWindow", "Target URL"))
        self.label_2.setText(_translate("MainWindow", "Enter the URL you want to scan for vulnerabilities"))
        self.LiveButton.setText(_translate("MainWindow", "Start Live Monitor"))
        self.StopButton.setText(_translate("MainWindow", "Stop Live"))
        self.Heading.setText(_translate("MainWindow", "Security Vulnerability Scanner "))
        self.label_3.setText(_translate("MainWindow", "Scan Result:"))
        self.SQLcheck.setText(_translate("MainWindow", "SQL Vulnerability"))
        self.XSScheck.setText(_translate("MainWindow", "XSS Vulnerability"))
        self.OpenRedirectcheck.setText(_translate("MainWindow", "Open Redirect"))
        self.SSLcheck.setText(_translate("MainWindow", "SSL Checker"))
        self.SecurityHeadcheck.setText(_translate("MainWindow", "Security Headers"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save Logs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
